
builds:
  -
    main: ./cmd/maliced
    binary: maliced
    env:
      - CGO_ENABLED=0
    goos:
      # - windows
      - darwin
      - linux
    goarch:
      - amd64
    flags: -buildmode=pie
    ldflags: |-
      -s
      -w
      -X github.com/maliceio/engine/malice/version.Version={{.Version}}
      -X github.com/maliceio/engine/malice/version.BuildTime={{.Date}}
      -X github.com/maliceio/engine/malice/version.GitCommit={{.Commit}}

archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  replacements:
    amd64: amd64
    darwin: macOS
    linux: linux
    windows: win

sign:
   artifacts: checksum

brew:
  github:
    owner: maliceio
    name: homebrew-tap
  folder: Formula
  homepage: "https://github.com/maliceio/engine"
  description: "Open Source Malware Analysis Framework."
  install: |
    bin.install "maliced"
  test: |
    system "#{bin}/maliced --version"

nfpm:
  vendor: MaliceIO
  homepage: https://malice.io/
  maintainer: Blacktop <github.com/blacktop>
  description: Open Source Malware Analysis Framework.
  license: Apache 2.0
  formats:
    - deb
    - rpm

snapcraft:
  name: maliced
  summary: Open Source Malware Analysis Framework Daemon.
  description: |
    Malice's background daemon/API.
  grade: stable
  confinement: strict
  apps:
    maliced:
      plugs: ["home", "network"]
      daemon: simple
