version: '3.3'

services:

  elasticsearch:
    image: malice/elasticsearch

  api:
    build:
      context: .
    image: malice/engine
    ports:
      - "3333:3333"
    environment:
      - PORT=3333

  httpie:
    build:
      context: .
      dockerfile: Dockerfile.httpie
    links:
      - api
